run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gosec
    - misspell

issues:
  exclude:
    - "SA1019" # Ignoring specific issues

