name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run tests
        run: go test ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          config: .golangci.yml

      - name: Build
        run: make build

      - name: Push to GitHub Container Registry
        run: |
          docker build -t ghcr.io/medevac-toolkit/medevac:latest .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/medevac-toolkit/medevac:latest
